apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: shipment-confirmed
spec:
  topic: shipment-registration-confirmed-events
  routes:
    default: /shipmentRegistered
  pubsubname: shippingpubsub
scopes:
- order-workflow
